version: '3.7'

services:
  store_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  my_proj:
    build: .
    command: python /usr/src/store/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/store
    ports:
      - 8000:8000
    depends_on:
      - store_db
volumes:
  postgres_data: